name: Deploy frontend and backend
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24 # Keep this in sync with the java version in pom.xml

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Import GPG key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Import SSH key
        run: ssh-add < ( echo "${{ secrets.SSH_KEY }}" )
          
      - name: Add Podman SSH connection
        run: |
          podman system connection add CONNECTION \
            --default \
            --identity ~/.ssh/id_ed25519 \
            "ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}"

      - name: Build Spring backend
        run: |
          cd spring-backend
          mvn --batch-mode clean install

      - name: Build and sign OCI image
        run: |
          cd spring-backend
          podman build \
            --tag spring_backend \
            --sign-by ${{ steps.import-gpg.fingerprint }}

      - name: Send image to server
        run: podman image scp spring_backend "root@$CONNECTION::"

      - name: Send the compose.yaml to the server
        run: scp spring-backend/compose.yaml "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:"

#TODO: Restart compose
